doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        result_cache: 'cache.dbal'
        types:
            email: Classroom\SharedContext\Infrastructure\Persistence\Doctrine\DBAL\Types\EmailType
            student_id: Classroom\StudentManagement\Infrastructure\Persistence\Doctrine\DBAL\Types\StudentIdType
            user_id: Classroom\IdentityAndAccess\Infrastructure\Persistence\Doctrine\DBAL\Types\UserIdType
            login_attempt_id: Classroom\IdentityAndAccess\Infrastructure\Persistence\Doctrine\DBAL\Types\LoginAttemptIdType
            login_history_id: Classroom\IdentityAndAccess\Infrastructure\Persistence\Doctrine\DBAL\Types\LoginHistoryIdType
            verification_token_id: Classroom\IdentityAndAccess\Infrastructure\Persistence\Doctrine\DBAL\Types\VerificationTokenIdType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false # problem here
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Classroom\SharedContext:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/SharedContext'
                prefix: 'Classroom\SharedContext\Domain\Model'
                is_bundle: false
            Classroom\StudentManagement:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/StudentManagement'
                prefix: 'Classroom\StudentManagement\Domain\Model'
                is_bundle: false
            Classroom\IdentityAndAccess:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/IdentityAndAccess'
                prefix: 'Classroom\IdentityAndAccess\Domain\Model'
                is_bundle: false
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
